In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as im
from sklearn.decomposition import TruncatedSVD
from skimage import color
from skimage import io
import numpy as np


img = color.rgb2gray(io.imread('/home/devyani/Desktop/papers/rose_test.jpeg'))
plt.imshow(img,cmap='gray')
plt.show()


U, s, V = np.linalg.svd(img)
#print(U.shape)
#print(np.diag(s).shape)
#print(V.shape)

k=20
U1=U[:,:k]
#print(U1.shape)
s1=s[0:k]
print(s1.shape)
V1=V[:k,:]
print(V1.shape)

img1= np.dot(np.dot(U1,np.diag(s1)),V1)
plt.imshow(img1,cmap='gray')
plt.show()
print(img1-img)

<Figure size 640x480 with 1 Axes>

(20,)
(20, 225)


<Figure size 640x480 with 1 Axes>

[[ 1.91355744e-04  1.91355744e-04  1.91355744e-04 ...  2.79460652e-04
   2.79460652e-04  2.79460652e-04]
 [ 1.91355744e-04  1.91355744e-04  1.91355744e-04 ...  2.79460652e-04
   2.79460652e-04  2.79460652e-04]
 [ 1.91355744e-04  1.91355744e-04  1.91355744e-04 ...  2.79460652e-04
   2.79460652e-04  2.79460652e-04]
 ...
 [-5.90240084e-04 -5.90240084e-04 -5.90240084e-04 ... -3.12309620e-05
  -3.12309620e-05 -3.12309620e-05]
 [-6.54268746e-04 -6.54268746e-04 -6.54268746e-04 ... -9.29527473e-05
  -9.29527473e-05 -9.29527473e-05]
 [ 2.81731060e-03  2.81731060e-03  2.81731060e-03 ... -4.44239193e-03
  -4.44239193e-03 -4.44239193e-03]]


In [2]:
X=np.array([[1 ,0 ,1, 0],[0 ,1, 0, 1]])
U, s, V = np.linalg.svd(X)
print(U)
print(np.dot(X,X.T))
print(V)



[[1. 0.]
 [0. 1.]]
[[2 0]
 [0 2]]
[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [-0.70710678  0.          0.70710678  0.        ]
 [ 0.         -0.70710678  0.          0.70710678]]
